# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0002_auto_20170605_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manfacturer',
            new_name='manufacturer',
        ),
    ]
